### ISSUE TITLE
gh-pages has entirely different commit history

### ISSUE THREAD

**Issue by JonathanHHenson** [CodingRainbow/asteroids-advanced#19]
Cannot current work with gh-pages as it has "an entirely different commit history"

**Comment by ada-lovecraft** [comment]
So, the way `gh-pages` is setup is somewhat confusing...

I've streamlined the process a bit. gh-pages is no longer a branch...

Instead, our site will host from the `/docs` directory on the master branch.

Please make changes to the hosted files in that directory.
