### ISSUE TITLE
Improved controls

### ISSUE THREAD

**Issue by JonathanHHenson** [CodingRainbow/asteroids-advanced#23]
Controls changed to:
- [x] Turn -> Rotates to face mouse pointer
- [x] Forward Thrust -> **W** or **UP** -> thrust force _x1_
- [x] Strafe Thrust -> **A/D** or **LEFT/RIGHT** -> thrust force _x0.5_
- [x] Backward Thrust -> **S** or **DOWN** -> thrust force _x0.1_
- [x] Stabilisation Thrusters toggle -> **SHIFT**

**Comment by MunWolf** [comment]
I got this nearly done but don't want to publish it until I can finish it with the planned physics system.

**Comment by MunWolf** [comment]
Close this

**Comment by JonathanHHenson** [comment]
Done
