### ISSUE TITLE
Refine asteroid splitting

### ISSUE THREAD

**Issue by MunWolf** [CodingRainbow/asteroids-advanced#9]
Make the asteroid splitting look more realistic by using the algorithm me and @NaveTK worked on in Gitter chat.

**Comment by NaveTK** [comment]
I'm on it, should be done in a couple of hours

**Comment by JonathanHHenson** [comment]
This code would run at the start of the Asteroid constructor to break up any splinter shaped asteroids

```
IF (A > minArea) {
  Error = |(PI - A / r ^ 2) / PI|
  IF (Error > Accepted) Snap()
} ELSE {
  dead = true
}
```

Snap will split the asteroid at the point which is closest to another point at least 2 indexes away.

**Comment by JonathanHHenson** [comment]
Done
